title: Manjitha Kularatne
logo: assets/img/my_image.jpg
description: Merging AI with Healthcare Innovation
theme: jekyll-theme-minimal
show_downloads: false

navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Resume
    url: /resume
  - title: Projects
    url: /projects
  - title: Contact
    url: /contact

social_links:
  - name: LinkedIn
    url: https://linkedin.com/in/manjitha-kularatne
  - name: GitHub
    url: https://github.com/manjithadulana98
  - name: Email
    url: mailto:manjitha456@gmail.com
